# Generated by Django 4.2.1 on 2023-05-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_board',
            name='good_bool',
            field=models.BooleanField(default=False),
        ),
    ]
