# Generated by Django 4.2.1 on 2023-05-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_user', '0002_notice_board_good_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
