# Generated by Django 4.2.1 on 2023-05-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_user', '0003_support_email_support_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
