# Generated by Django 4.2.1 on 2023-05-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_user', '0004_resume_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='support_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
