# Generated by Django 4.2.1 on 2023-05-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_user', '0005_employment_support_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
