# Generated by Django 4.2.1 on 2023-05-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_user', '0006_support_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
